
import { Inter } from "next/font/google";
import "./globals.css";
import {Provider} from "./(NextuiProvider)/Provider";
import Navbar from "@/components/Navbar/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import ChooseRole from "@/components/chooseRole/ChooseRole"
import { frFR } from "@clerk/localizations";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  


  return (
   
    <html lang="en">
      
         <body className={inter.className}>
         <ClerkProvider localization={frFR}  appearance={{
      variables: {
          colorPrimary: "#28B463",
          
      },
    
      }}  publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
         
         <Provider>
         <Navbar />

          {children}
         </Provider>
    </ClerkProvider>

          </body>
    </html>
  );
}
